import { Metadata, Viewport } from 'next'
import './globals.css'
import { cn } from "@/utils/lib/utils";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: '#000000',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export const metadata: Metadata = {
  title: 'LakazHub - Rental Property Marketplace',
  description: 'Find your perfect rental property with LakazHub',
  manifest: '/manifest.json',
  keywords: [
    'LakazHub', 'rent property Mauritius', 'houses for rent Mauritius', 'apartments Mauritius', 'property rental Mauritius',
    'Mauritius real estate', 'Mauritius property portal', 'landlord Mauritius', 'tenant Mauritius', 'rental listings Mauritius',
    'long term rental Mauritius', 'short term rental Mauritius', 'Mauritius rental platform', 'LakazHub Mauritius', 'LakazHub property',
    'LakazHub apartments', 'LakazHub houses', 'LakazHub rental', 'LakazHub landlord', 'LakazHub tenant', 'LakazHub Mauritius property'
  ],
  metadataBase: new URL('https://lakazhub.com'),
  openGraph: {
    title: 'LakazHub - Rent Properties in Mauritius',
    description: 'Easily rent and find properties, houses, and apartments across Mauritius. Connect landlords and tenants seamlessly with LakazHub.',
    url: 'https://lakazhub.com/',
    type: 'website',
    images: [
      {
        url: '/lakaz-hub.png',
        width: 1200,
        height: 630,
        alt: 'LakazHub Mauritius Property Rental'
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    site: '@lakazhub',
    title: 'LakazHub - Rent Properties in Mauritius',
    description: 'Find, rent, and manage properties in Mauritius. The #1 property rental platform for landlords and tenants.',
    images: ['/lakaz-hub.png']
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'LakazHub'
  },
  formatDetection: {
    telephone: false
  },
  authors: [{ name: 'LakazHub', url: 'https://lakazhub.com/' }]
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* SEO meta tags */}
        <meta name="description" content="Find, rent, and manage houses, apartments, and properties in Mauritius easily with LakazHub. The #1 property rental platform for landlords and tenants in Mauritius." />
        <meta name="keywords" content="LakazHub, rent property Mauritius, houses for rent Mauritius, apartments Mauritius, property rental Mauritius, Mauritius real estate, Mauritius property portal, landlord Mauritius, tenant Mauritius, rental listings Mauritius, long term rental Mauritius, short term rental Mauritius, Mauritius rental platform, LakazHub Mauritius, LakazHub property, LakazHub apartments, LakazHub houses, LakazHub rental, LakazHub landlord, LakazHub tenant, LakazHub Mauritius property" />
        <meta name="author" content="LakazHub" />
        <meta property="og:title" content="LakazHub - Rent Properties in Mauritius" />
        <meta property="og:description" content="Easily rent and find properties, houses, and apartments across Mauritius. Connect landlords and tenants seamlessly with LakazHub." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://lakazhub.com/" />
        <meta property="og:image" content="/lakaz-hub.png" />
        <meta name="robots" content="index, follow" />
        {/* Add this line for better PWA experience */}
        <meta name="description" content="Connect landlords and tenants seamlessly with LakazHub" />
        {/* Add both meta tags for maximum compatibility */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* Favicon and PWA icons */}
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="canonical" href="https://lakazhub.com/" />
        {/* Add any other icons generated by RealFaviconGenerator */}
        {/* iOS PWA meta tags */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="LakazHub" />
        {/* Apple Touch Icons - use apple-icon.png for all sizes */}
        <link rel="apple-touch-icon" href="/apple-icon.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon.png" />
        
        {/* iOS Splash Screens - Using a simplified approach */}
        <link rel="apple-touch-startup-image" href="/apple-icon.png" media="(device-width: 375px)" />
        <link rel="apple-touch-startup-image" href="/apple-icon.png" media="(device-width: 768px)" />
        
        {/* Apple Touch Icon - using your existing image */}
        <link rel="apple-touch-icon" href="/apple-icon.png" />
        {/* (Optional) Splash screens for iOS devices */}
        {/* <link rel="apple-touch-startup-image" href="/splash/apple-splash-2048-2732.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" /> */}
      </head>
      <body className={cn(inter.className, "min-h-screen bg-black")}>
        {children}
      </body>
    </html>
  )
}